server:
  port: 8000
  error:
    include-message: always
spring:
  application:
    name: "Video Sharing App"
  datasource:
    username: root
    password: 01712274429
    url: jdbc:mysql://localhost:3306/video_sharing_database
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000