logging:
  level:
    org:
      springframework:
        security: trace
      hibernate:
        stat: debug
server:
  servlet:
    context-path: /
  port: 8000
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
#    static-path-pattern: /demo/**
  application:
    name: "Video Sharing App"
  datasource:
    username: root
    password: 01712274429
    url: jdbc:mysql://localhost:3306/video_sharing_database
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        generate_statistics: true


  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 3000
          write timeout: 5000
  web:
    resources:
      add-mappings: true
